export type ApprovedInventorySeedItem = {
  code: string;
  name: string;
  quantity: number;
  category: string;
  subcategory: string;
  type: 'RETURNABLE' | 'CONSUMABLE';
  unit: string;
  minStock: number;
  sortOrder: number;
};

export const approvedInventorySeed: ApprovedInventorySeedItem[] = [
  { code: 'OP001', name: 'مصدات مائلة', quantity: 3, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'معدات دفاع وتدريب تكتيكي', type: 'RETURNABLE', unit: 'قطعة', minStock: 2, sortOrder: 1 },
  { code: 'OP002', name: 'مصدات مستطيلة', quantity: 6, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'معدات دفاع وتدريب تكتيكي', type: 'RETURNABLE', unit: 'قطعة', minStock: 2, sortOrder: 2 },
  { code: 'OP003', name: 'خوذة رأس', quantity: 19, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'معدات حماية شخصية', type: 'RETURNABLE', unit: 'قطعة', minStock: 4, sortOrder: 3 },
  { code: 'OP004', name: 'مصدات يد', quantity: 16, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'معدات دفاع وتدريب تكتيكي', type: 'RETURNABLE', unit: 'قطعة', minStock: 4, sortOrder: 4 },
  { code: 'OP005', name: 'سترة حماية', quantity: 20, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'معدات حماية شخصية', type: 'RETURNABLE', unit: 'قطعة', minStock: 4, sortOrder: 5 },
  { code: 'OP006', name: 'قفازة يد', quantity: 36, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'معدات حماية شخصية', type: 'RETURNABLE', unit: 'قطعة', minStock: 6, sortOrder: 6 },
  { code: 'OP007', name: 'مسدس', quantity: 15, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'أسلحة تدريبية', type: 'RETURNABLE', unit: 'قطعة', minStock: 3, sortOrder: 7 },
  { code: 'OP008', name: 'كلبشات', quantity: 9, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'أدوات ضبط وتقييد', type: 'RETURNABLE', unit: 'قطعة', minStock: 2, sortOrder: 8 },
  { code: 'OP009', name: 'مفاتيح كلبشات', quantity: 4, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'أدوات ضبط وتقييد', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 9 },
  { code: 'OP010', name: 'شنطة دمية اسعافات أولية', quantity: 2, category: 'الإسعافات الأولية والسلامة', subcategory: 'حقائب ومحاكاة إسعافية', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 10 },
  { code: 'OP011', name: 'مصدات يد كبيرة', quantity: 4, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'معدات دفاع وتدريب تكتيكي', type: 'RETURNABLE', unit: 'قطعة', minStock: 2, sortOrder: 11 },
  { code: 'OP012', name: 'دمية تدريب دفاع عن النفس', quantity: 2, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'دمى ومحاكاة تدريبية', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 12 },
  { code: 'OP013', name: 'دمية اسعافات أولية', quantity: 1, category: 'الإسعافات الأولية والسلامة', subcategory: 'دمى ومحاكاة إسعافية', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 13 },
  { code: 'OP014', name: 'استاند تدريب البوكس', quantity: 2, category: 'الأدوات الرياضية والتدريب البدني', subcategory: 'معدات لياقة وتدريب بدني', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 14 },
  { code: 'OP015', name: 'حبل قفز', quantity: 5, category: 'الأدوات الرياضية والتدريب البدني', subcategory: 'معدات لياقة وتدريب بدني', type: 'RETURNABLE', unit: 'قطعة', minStock: 2, sortOrder: 15 },
  { code: 'OP016', name: 'ربطة شد الحبل', quantity: 5, category: 'الأدوات الرياضية والتدريب البدني', subcategory: 'معدات لياقة وتدريب بدني', type: 'RETURNABLE', unit: 'قطعة', minStock: 2, sortOrder: 16 },
  { code: 'OP017', name: 'شنطة إسعافات أولية', quantity: 2, category: 'الإسعافات الأولية والسلامة', subcategory: 'حقائب إسعافية', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 17 },
  { code: 'OP018', name: 'أطباق 10 كيلو', quantity: 4, category: 'الأدوات الرياضية والتدريب البدني', subcategory: 'أوزان رياضية', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 18 },
  { code: 'OP019', name: 'سكين', quantity: 20, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'أسلحة تدريبية', type: 'RETURNABLE', unit: 'قطعة', minStock: 4, sortOrder: 19 },
  { code: 'OP020', name: 'كيتل بل 4 كيلو', quantity: 7, category: 'الأدوات الرياضية والتدريب البدني', subcategory: 'أوزان رياضية', type: 'RETURNABLE', unit: 'قطعة', minStock: 2, sortOrder: 20 },
  { code: 'OP021', name: 'ملفات', quantity: 75, category: 'القرطاسية والمواد المكتبية', subcategory: 'حفظ وتنظيم', type: 'CONSUMABLE', unit: 'قطعة', minStock: 10, sortOrder: 21 },
  { code: 'OP022', name: 'نوته', quantity: 945, category: 'القرطاسية والمواد المكتبية', subcategory: 'دفاتر وملاحظات', type: 'CONSUMABLE', unit: 'قطعة', minStock: 50, sortOrder: 22 },
  { code: 'OP023', name: 'أقلام', quantity: 2148, category: 'القرطاسية والمواد المكتبية', subcategory: 'أدوات كتابة', type: 'CONSUMABLE', unit: 'قطعة', minStock: 100, sortOrder: 23 },
  { code: 'OP024', name: 'حزام تكتيكي لحمل المسدس', quantity: 20, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'ملحقات تكتيكية', type: 'RETURNABLE', unit: 'قطعة', minStock: 4, sortOrder: 24 },
  { code: 'OP025', name: 'جراب مسدس', quantity: 20, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'ملحقات تكتيكية', type: 'RETURNABLE', unit: 'قطعة', minStock: 4, sortOrder: 25 },
  { code: 'OP026', name: 'أقلام سبورة', quantity: 172, category: 'القرطاسية والمواد المكتبية', subcategory: 'مستلزمات عرض وشرح', type: 'CONSUMABLE', unit: 'قطعة', minStock: 20, sortOrder: 26 },
  { code: 'OP027', name: 'دباسات', quantity: 0, category: 'القرطاسية والمواد المكتبية', subcategory: 'أدوات مكتبية', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 27 },
  { code: 'OP028', name: 'قلم تحديد هاي لايت', quantity: 0, category: 'القرطاسية والمواد المكتبية', subcategory: 'أدوات كتابة', type: 'CONSUMABLE', unit: 'قطعة', minStock: 5, sortOrder: 28 },
  { code: 'OP029', name: 'براية أقلام رصاص', quantity: 0, category: 'القرطاسية والمواد المكتبية', subcategory: 'أدوات مكتبية', type: 'CONSUMABLE', unit: 'قطعة', minStock: 2, sortOrder: 29 },
  { code: 'OP030', name: 'مسطرة', quantity: 13, category: 'القرطاسية والمواد المكتبية', subcategory: 'أدوات مكتبية', type: 'CONSUMABLE', unit: 'قطعة', minStock: 3, sortOrder: 30 },
  { code: 'OP031', name: 'دبابيس دباسة', quantity: 32, category: 'القرطاسية والمواد المكتبية', subcategory: 'أدوات مكتبية', type: 'CONSUMABLE', unit: 'علبة', minStock: 5, sortOrder: 31 },
  { code: 'OP032', name: 'قلم رصاص', quantity: 12, category: 'القرطاسية والمواد المكتبية', subcategory: 'أدوات كتابة', type: 'CONSUMABLE', unit: 'قطعة', minStock: 4, sortOrder: 32 },
  { code: 'OP033', name: 'مشابك كلبس أسود كبير', quantity: 0, category: 'القرطاسية والمواد المكتبية', subcategory: 'أدوات مكتبية', type: 'CONSUMABLE', unit: 'علبة', minStock: 2, sortOrder: 33 },
  { code: 'OP034', name: 'مثلثات هندسية', quantity: 19, category: 'القرطاسية والمواد المكتبية', subcategory: 'أدوات مكتبية', type: 'CONSUMABLE', unit: 'مجموعة', minStock: 3, sortOrder: 34 },
  { code: 'OP035', name: 'مساحة', quantity: 30, category: 'القرطاسية والمواد المكتبية', subcategory: 'أدوات مكتبية', type: 'CONSUMABLE', unit: 'قطعة', minStock: 5, sortOrder: 35 },
  { code: 'OP036', name: 'ملفات دوكس فايل كبير', quantity: 44, category: 'القرطاسية والمواد المكتبية', subcategory: 'حفظ وتنظيم', type: 'CONSUMABLE', unit: 'قطعة', minStock: 8, sortOrder: 36 },
  { code: 'OP037', name: 'VR مجموعة', quantity: 9, category: 'الواقع الافتراضي والتصوير والمحاكاة', subcategory: 'أنظمة واقع افتراضي', type: 'RETURNABLE', unit: 'مجموعة', minStock: 2, sortOrder: 37 },
  { code: 'OP038', name: 'لابتوب تحقيق مواقع الحريق لينوفو', quantity: 3, category: 'الأجهزة التقنية والحاسب', subcategory: 'حواسيب محمولة متخصصة', type: 'RETURNABLE', unit: 'جهاز', minStock: 1, sortOrder: 38 },
  { code: 'OP039', name: 'شنطة كبيرة VR', quantity: 2, category: 'الواقع الافتراضي والتصوير والمحاكاة', subcategory: 'ملحقات واقع افتراضي', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 39 },
  { code: 'OP040', name: 'شنطة معدات تصوير VR', quantity: 1, category: 'الواقع الافتراضي والتصوير والمحاكاة', subcategory: 'ملحقات تصوير ومحاكاة', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 40 },
  { code: 'OP041', name: 'ستاند كاميرا', quantity: 5, category: 'الواقع الافتراضي والتصوير والمحاكاة', subcategory: 'حوامل وتجهيزات تصوير', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 41 },
  { code: 'OP042', name: 'لابتوبات التدريب', quantity: 35, category: 'الأجهزة التقنية والحاسب', subcategory: 'حواسيب محمولة', type: 'RETURNABLE', unit: 'جهاز', minStock: 5, sortOrder: 42 },
  { code: 'OP043', name: 'ريموت', quantity: 19, category: 'الأجهزة التقنية والحاسب', subcategory: 'ملحقات تقنية', type: 'RETURNABLE', unit: 'قطعة', minStock: 3, sortOrder: 43 },
  { code: 'OP044', name: 'فرش اسفنج تدريب', quantity: 10, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'معدات تدريب أرضية', type: 'RETURNABLE', unit: 'قطعة', minStock: 3, sortOrder: 44 },
  { code: 'OP045', name: 'عصا تدريب', quantity: 20, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'أدوات تدريب ميداني', type: 'RETURNABLE', unit: 'قطعة', minStock: 4, sortOrder: 45 },
  { code: 'OP046', name: 'مراية فحص وتفتيش السيارات (شكل مستطيل)', quantity: 2, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'أدوات تفتيش وفحص', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 46 },
  { code: 'OP047', name: 'مراية فحص وتفتيش السيارات (شكل دائري)', quantity: 1, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'أدوات تفتيش وفحص', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 47 },
  { code: 'OP048', name: 'نظارة VR', quantity: 20, category: 'الواقع الافتراضي والتصوير والمحاكاة', subcategory: 'أنظمة واقع افتراضي', type: 'RETURNABLE', unit: 'قطعة', minStock: 3, sortOrder: 48 },
  { code: 'OP049', name: 'كرت حفظ بيانات نظارة VR', quantity: 20, category: 'الواقع الافتراضي والتصوير والمحاكاة', subcategory: 'ملحقات واقع افتراضي', type: 'RETURNABLE', unit: 'قطعة', minStock: 3, sortOrder: 49 },
  { code: 'OP050', name: 'سماعة VR', quantity: 20, category: 'الواقع الافتراضي والتصوير والمحاكاة', subcategory: 'أنظمة واقع افتراضي', type: 'RETURNABLE', unit: 'قطعة', minStock: 3, sortOrder: 50 },
  { code: 'OP051', name: 'لابتوب VR', quantity: 1, category: 'الأجهزة التقنية والحاسب', subcategory: 'حواسيب محمولة متخصصة', type: 'RETURNABLE', unit: 'جهاز', minStock: 1, sortOrder: 51 },
  { code: 'OP052', name: 'فلاش ميموري ساند ديسك', quantity: 16, category: 'الأجهزة التقنية والحاسب', subcategory: 'وسائط تخزين', type: 'RETURNABLE', unit: 'قطعة', minStock: 3, sortOrder: 52 },
  { code: 'OP053', name: 'حامل فلاش ميموري اوريكو (عدد 4 فلاشات)', quantity: 4, category: 'الأجهزة التقنية والحاسب', subcategory: 'وسائط تخزين', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 53 },
  { code: 'OP054', name: 'كيبل شاحن شنطة VR', quantity: 2, category: 'الواقع الافتراضي والتصوير والمحاكاة', subcategory: 'ملحقات واقع افتراضي', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 54 },
  { code: 'OP055', name: 'كيبل شاحن لابتوب VR', quantity: 1, category: 'الأجهزة التقنية والحاسب', subcategory: 'ملحقات تقنية', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 55 },
  { code: 'OP056', name: 'مسند ثلاثي لحمل الكاميرا', quantity: 1, category: 'الواقع الافتراضي والتصوير والمحاكاة', subcategory: 'حوامل وتجهيزات تصوير', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 56 },
  { code: 'OP057', name: 'كاميرا 360 انستا', quantity: 1, category: 'الواقع الافتراضي والتصوير والمحاكاة', subcategory: 'كاميرات ومحاكاة', type: 'RETURNABLE', unit: 'جهاز', minStock: 1, sortOrder: 57 },
  { code: 'OP058', name: 'بطارية الكاميرا', quantity: 3, category: 'الواقع الافتراضي والتصوير والمحاكاة', subcategory: 'ملحقات تصوير ومحاكاة', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 58 },
  { code: 'OP059', name: 'كرت حفظ البيانات', quantity: 4, category: 'الأجهزة التقنية والحاسب', subcategory: 'وسائط تخزين', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 59 },
  { code: 'OP060', name: 'حامل كرت حفظ البيانات', quantity: 4, category: 'الأجهزة التقنية والحاسب', subcategory: 'وسائط تخزين', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 60 },
  { code: 'OP061', name: 'فلاش ميموري انكر', quantity: 1, category: 'الأجهزة التقنية والحاسب', subcategory: 'وسائط تخزين', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 61 },
  { code: 'OP062', name: 'كيبل يو اس بي', quantity: 2, category: 'الأجهزة التقنية والحاسب', subcategory: 'ملحقات تقنية', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 62 },
  { code: 'OP063', name: 'سبورة فليب شارت', quantity: 9, category: 'التجهيزات التدريبية والقاعة', subcategory: 'وسائل عرض وتيسير', type: 'RETURNABLE', unit: 'قطعة', minStock: 2, sortOrder: 63 },
  { code: 'OP064', name: 'عصا فحص التفتيش', quantity: 1, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'أدوات تفتيش وفحص', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 64 },
  { code: 'OP065', name: 'ورق طباعة A4', quantity: 6, category: 'القرطاسية والمواد المكتبية', subcategory: 'ورق ومطبوعات', type: 'CONSUMABLE', unit: 'رزمة', minStock: 2, sortOrder: 65 },
  { code: 'OP071', name: 'أغلفة شهادات', quantity: 90, category: 'الهويات والشهادات والمطبوعات', subcategory: 'شهادات وأغلفة', type: 'CONSUMABLE', unit: 'قطعة', minStock: 15, sortOrder: 71 },
  { code: 'OP073', name: 'أجهزة كمبيوتر ديل', quantity: 36, category: 'الأجهزة التقنية والحاسب', subcategory: 'حواسيب مكتبية', type: 'RETURNABLE', unit: 'جهاز', minStock: 4, sortOrder: 73 },
  { code: 'OP074', name: 'كشاف', quantity: 19, category: 'معدات التدريب الأمني والدفاعي', subcategory: 'أدوات تفتيش وفحص', type: 'RETURNABLE', unit: 'قطعة', minStock: 3, sortOrder: 74 },
  { code: 'OP075', name: 'خرامة ورق', quantity: 5, category: 'القرطاسية والمواد المكتبية', subcategory: 'أدوات مكتبية', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 75 },
  { code: 'OP076', name: 'صمغ', quantity: 7, category: 'القرطاسية والمواد المكتبية', subcategory: 'مواد مكتبية مساعدة', type: 'CONSUMABLE', unit: 'قطعة', minStock: 2, sortOrder: 76 },
  { code: 'OP077', name: 'ظرف كبير', quantity: 100, category: 'القرطاسية والمواد المكتبية', subcategory: 'مظاريف وحفظ', type: 'CONSUMABLE', unit: 'قطعة', minStock: 10, sortOrder: 77 },
  { code: 'OP078', name: 'ظرف وسط', quantity: 97, category: 'القرطاسية والمواد المكتبية', subcategory: 'مظاريف وحفظ', type: 'CONSUMABLE', unit: 'قطعة', minStock: 10, sortOrder: 78 },
  { code: 'OP079', name: 'ظرف صغير', quantity: 36, category: 'القرطاسية والمواد المكتبية', subcategory: 'مظاريف وحفظ', type: 'CONSUMABLE', unit: 'قطعة', minStock: 5, sortOrder: 79 },
  { code: 'OP080', name: 'مشابك كلبس أسود صغير', quantity: 8, category: 'القرطاسية والمواد المكتبية', subcategory: 'أدوات مكتبية', type: 'CONSUMABLE', unit: 'علبة', minStock: 2, sortOrder: 80 },
  { code: 'OP081', name: 'ورق أصفر لاصق', quantity: 1, category: 'القرطاسية والمواد المكتبية', subcategory: 'مستلزمات مكتبية', type: 'CONSUMABLE', unit: 'قطعة', minStock: 1, sortOrder: 81 },
  { code: 'OP082', name: 'مغناطيس ألوان', quantity: 16, category: 'التجهيزات التدريبية والقاعة', subcategory: 'وسائل عرض وتيسير', type: 'CONSUMABLE', unit: 'قطعة', minStock: 3, sortOrder: 82 },
  { code: 'OP083', name: 'تعليقة بطاقة', quantity: 2455, category: 'الهويات والشهادات والمطبوعات', subcategory: 'بطاقات وتعريف', type: 'CONSUMABLE', unit: 'قطعة', minStock: 100, sortOrder: 83 },
  { code: 'OP084', name: 'أغلفة بطاقات', quantity: 1002, category: 'الهويات والشهادات والمطبوعات', subcategory: 'بطاقات وتعريف', type: 'CONSUMABLE', unit: 'قطعة', minStock: 75, sortOrder: 84 },
  { code: 'OP085', name: 'كيس إسعافات أولية', quantity: 1, category: 'الإسعافات الأولية والسلامة', subcategory: 'حقائب إسعافية', type: 'RETURNABLE', unit: 'قطعة', minStock: 1, sortOrder: 85 },
  { code: 'OP086', name: 'فليب شارت', quantity: 99, category: 'التجهيزات التدريبية والقاعة', subcategory: 'وسائل عرض وتيسير', type: 'RETURNABLE', unit: 'قطعة', minStock: 8, sortOrder: 86 },
];
